FROM node:18.11.0

WORKDIR /usr/src/app

COPY package.json .

RUN rm yarn.lock || true
RUN rm package-lock.json || true
RUN yarn install
RUN yarn pm2 install typescript

RUN ln -sf /usr/share/zoneinfo/Asia/Seoul /etc/localtime

COPY . .

ARG NOTION_TOKEN
ENV NOTION_TOKEN=$NOTION_TOKEN

ARG NOTION_PAGE_URL
ENV NOTION_PAGE_URL=$NOTION_PAGE_URL

ARG NOTION_DOMAIN
ENV NOTION_DOMAIN=$NOTION_DOMAIN

ARG NOTION_TODO_DATABASE_ID
ENV NOTION_TODO_DATABASE_ID=$NOTION_TODO_DATABASE_ID

ARG NOTION_BLOG_DATABASE_ID
ENV NOTION_BLOG_DATABASE_ID=$NOTION_BLOG_DATABASE_ID

ARG NOTION_INTERVIEW_DATABASE_ID
ENV NOTION_INTERVIEW_DATABASE_ID=$NOTION_INTERVIEW_DATABASE_ID

ARG NOTION_MEMBER_SNS_DATABASE_ID
ENV NOTION_MEMBER_SNS_DATABASE_ID=$NOTION_MEMBER_SNS_DATABASE_ID

ARG NOTION_PORTFOLIO_DATABASE_ID
ENV NOTION_PORTFOLIO_DATABASE_ID=$NOTION_PORTFOLIO_DATABASE_ID

ARG NOTION_REF_SITES_DATABASE_ID
ENV NOTION_REF_SITES_DATABASE_ID=$NOTION_REF_SITES_DATABASE_ID

ARG NOTION_PROJECT_IDEAS_DATABASE_ID
ENV NOTION_PROJECT_IDEAS_DATABASE_ID=$NOTION_PROJECT_IDEAS_DATABASE_ID

ARG NOTION_MEETING_SCHEDULE_DATABASE_ID
ENV NOTION_MEETING_SCHEDULE_DATABASE_ID=$NOTION_MEETING_SCHEDULE_DATABASE_ID

EXPOSE 3000/udp

CMD ["yarn","pm2-runtime","pm2.config.json"]